<template>
  <q-page
    :style-fn="
      (offset, height) => ({
        height: `${height - offset}px`,
        minHeight: `${height - offset}px`,
      })
    "
    class="column relative no-wrap compact-scrollbar"
  >
    <chat-page
      ref="chatPage"
      :initial_conversations="initial_conversations"
      style="flex-grow: 1; padding-bottom: 12rem"
      :dark="$q.dark.isActive"
    ></chat-page>
    <user-prompt
      :last-prompt="
        initial_conversations[initial_conversations.length - 1].prompt
      "
      style="position: absolute; bottom: 0; left: 0; right: 0"
      :is-generating="!!chatPage?.isGenerating"
      :generated="!!chatPage?.conversations.length"
      :dark="$q.dark.isActive"
      @prompt="request"
      @stop-generation="chatPage?.cancelTypewriter()"
    ></user-prompt>
  </q-page>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import ChatPage from '../components/ChatPage.vue';
import UserPrompt from '../components/UserPrompt.vue';

import type { Conversation } from '../components/ChatPage.vue';

const initial_conversations = ref<Conversation[]>([]);

const chatPage = ref<InstanceType<typeof ChatPage>>();

const lorem =
  'Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam ducimus facere quam unde sit quae eveniet fugiat deleniti quisquam obcaecati nemo quod, rerum, harum consequuntur culpa, id neque! Accusamus, nobis.';

const request = (prompt: string) => {
  // fake api call
  setTimeout(() => {
    chatPage.value?.addConversation({
      prompt: prompt,
      response: lorem,
    });
  }, 500);
};

for (let i = 0; i < 10; i++) {
  initial_conversations.value.push({
    prompt: `this is autogenerated ${i}`,
    response: lorem,
  });
}
</script>
